export const DEFAULT_BUYBACK_RATE = 0;

export const BUYBACK_CATEGORIES: Array<{ rate: number; items: readonly string[] }> = [
  {
    rate: 0.9,
    items: [
  "Ancient Coordinates Database",
  "Neural Network Analyzer",
  "Sleeper Data Library",
    "Sleeper Drone AI Nexus",
  ] },
  {
    rate: 0.85,
    items: [
  "Bacteria",
  "Biocells",
  "Biofuels",
  "Biomass",
  "Biotech Research Reports",
  "Broadcast Node",
  "Camera Drones",
  "Chiral Structures",
  "Condensates",
  "Construction Blocks",
  "Consumer Electronics",
  "Coolant",
  "Cryoprotectant Solution",
  "Data Chips",
  "Electrolytes",
  "Enriched Uranium",
  "Fertilizer",
  "Gel-Matrix Biopaste",
  "Genetically Enhanced Livestock",
  "Guidance Systems",
  "Hazmat Detection Systems",
  "Hermetic Membranes",
  "High-Tech Transmitters",
  "Industrial Explosives",
  "Industrial Fibers",
  "Integrity Response Drones",
  "Livestock",
  "Mechanical Parts",
  "Microfiber Shielding",
  "Miniature Electronics",
  "Nanites",
  "Nano-Factory",
  "Neocoms",
  "Nuclear Reactors",
  "Organic Mortar Applicators",
  "Oxides",
  "Oxidizing Compound",
  "Oxygen",
  "Planetary Vehicles",
  "Plasmoids",
  "Polyaramids",
  "Polytextiles",
  "Precious Metals",
  "Proteins",
  "Reactive Metals",
  "Recursive Computing Module",
  "Robotics",
  "Rocket Fuel",
  "Self-Harmonizing Power Core",
  "Silicate Glass",
  "Silicon",
  "Smartfab Units",
  "Sterile Conduits",
  "Supercomputers",
  "Superconductors",
  "Supertensile Plastics",
  "Synthetic Oil",
  "Synthetic Synapses",
  "Test Cultures",
  "Toxic Metals",
  "Transcranial Microcontrollers",
  "Transmitter",
  "Ukomi Superconductors",
  "Vaccines",
  "Viral Agent",
  "Water",
  "Water-Cooled CPU",
    "Wetware Mainframe",
  ] },
  {
    rate: 0.85,
    items: [
  "Compressed Amber Cytoserocin",
  "Compressed Amber Mykoserocin",
  "Compressed Azure Cytoserocin",
  "Compressed Azure Mykoserocin",
  "Compressed Celadon Cytoserocin",
  "Compressed Celadon Mykoserocin",
  "Compressed Fullerite-C28",
  "Compressed Fullerite-C32",
  "Compressed Fullerite-C320",
  "Compressed Fullerite-C50",
  "Compressed Fullerite-C540",
  "Compressed Fullerite-C60",
  "Compressed Fullerite-C70",
  "Compressed Fullerite-C72",
  "Compressed Fullerite-C84",
  "Compressed Golden Cytoserocin",
  "Compressed Golden Mykoserocin",
  "Compressed Lime Cytoserocin",
  "Compressed Lime Mykoserocin",
  "Compressed Malachite Cytoserocin",
  "Compressed Malachite Mykoserocin",
  "Compressed Vermillion Cytoserocin",
  "Compressed Vermillion Mykoserocin",
  "Compressed Viridian Cytoserocin",
    "Compressed Viridian Mykoserocin",
  ] },
  {
    rate: 0.75,
    items: [
  "AEGIS Covert Operations Reports",
  "AEGIS Fortification Schematics",
  "AEGIS Personnel File Backups",
    "AEGIS Security Patrol Reports",
  ] },
  {
    rate: 0.9,
    items: [
  "Accelerant Decryptor",
  "Attainment Decryptor",
  "Augmentation Decryptor",
  "Intact Armor Nanobot",
  "Intact Hull Section",
  "Intact Power Cores",
  "Intact Thruster Sections",
  "Intact Weapon Subroutines",
  "Malfunctioning Armor Nanobot",
  "Malfunctioning Hull Section",
  "Malfunctioning Power Cores",
  "Malfunctioning Thruster Sections",
  "Malfunctioning Weapon Subroutines",
  "Optimized Attainment Decryptor",
  "Optimized Augmentation Decryptor",
  "Parity Decryptor",
  "Process Decryptor",
  "Small Intact Hull Section",
  "Small Malfunctioning Hull Section",
  "Small Wrecked Hull Section",
  "Symmetry Decryptor",
  "Wrecked Armor Nanobot",
  "Wrecked Hull Section",
  "Wrecked Power Cores",
  "Wrecked Thruster Sections",
    "Wrecked Weapon Subroutines",
  ] },
  {
    rate: 0.85,
    items: [
  "Admixti Mutanite",
  "Amperum Mutanite",
  "Armor Mutaplasmid Residue",
  "Astronautic Mutaplasmid Residue",
  "Conflagrati Mutanite",
  "Crystalline Isogen-10",
  "Damage Control Mutaplasmid Residue",
  "Drone Mutaplasmid Residue",
  "Engineering Mutaplasmid Residue",
  "Fluctuating Entropic Regulator",
  "Large Mutaplasmid Residue",
  "Medium Mutaplasmid Residue",
  "Peregrinus Mutanite",
  "Shield Mutaplasmid Residue",
  "Small Mutaplasmid Residue",
  "Solis Mutanite",
  "Stasis Webifier Mutaplasmid Residue",
  "Tenebraet Mutanite",
  "Unaligned Dekaisogen",
  "Warp Disruption Mutaplasmid Residue",
  "Weapon Upgrade Mutaplasmid Residue",
  "X-Large Mutaplasmid Residue",
    "Zero-Point Condensate",
  ] },
  {
    rate: 0.9,
    items: [
  "Alloyed Tritanium Bar",
  "Ancient Radar Decorrelator",
  "Armor Plates",
  "Artificial Neural Network",
  "Authority Datacore",
  "Beacon Datacore",
  "Breaking Point Parameters",
  "Broken Drone Transceiver",
  "Burned Logic Circuit",
  "Capacitor Console",
  "Cartesian Temporal Coordinator",
  "Central System Controller",
  "Charred Micro Circuit",
  "Conductive Polymer",
  "Conductive Thermoplastic",
  "Contaminated Lorentz Fluid",
  "Contaminated Nanite Compound",
  "Contraband Data",
  "Current Pump",
  "Damaged Artificial Neural Network",
  "Defective Current Pump",
  "Defensive Control Node",
  "Drone Transceiver",
  "Electromagnetic Metaprismatic Sheeting",
  "Electromechanical Hull Sheeting",
  "Emergent Combat Analyzer",
  "Emergent Combat Intelligence",
  "Encrypted 'Istina' Data",
  "Enhanced Ward Console",
  "Eradicator Datacore",
  "Faraday Force Magnetometer",
  "Federal Encryption Key",
  "Fragmented Observations",
  "Fried Interface Circuit",
  "Fused Nanomechanical Engines",
  "Gleaned Correspondence",
  "Gleaned Directive",
  "Gleaned Static",
  "Heuristic Selfassemblers",
  "Hyperbolic Metatransistor Array",
  "Imperial Exploit Log",
  "Impetus Console",
  "Insurgent Trojan Fragments",
  "Intact Armor Plates",
  "Intact Shield Emitter",
  "Interface Circuit",
  "Jailer Datacore",
  "Jump Drive Control Nexus",
  "Logic Circuit",
  "Lorentz Fluid",
  "Malfunctioning Shield Emitter",
  "Megacorp Transaction Thread",
  "Melted Capacitor Console",
  "Melted Nanoribbons",
  "Micro Circuit",
  "Military Stasis Pods",
  "Modified Fluid Router",
  "Modified Sleeper Corpse",
  "Nanite Compound",
  "Neurovisual Input Matrix",
  "Observatory Spectrography",
  "PDN Passkey",
  "Powdered C-540 Graphite",
  "Power Circuit",
  "Power Conduit",
  "Resonance Calibration Matrix",
  "Restricted Hyperspace Telemetry",
  "Scorched Microgravimeter",
  "Scorched Telemetry Processor",
  "Simulated Baseliner",
  "Single-crystal Superalloy I-beam",
  "Smashed Trigger Unit",
  "Synthetic Aperture Ladar Receiver",
  "Tangled Power Conduit",
  "Tekton Forked Packet",
  "Telemetry Processor",
  "Thermoelectric Catalysts",
  "Thruster Console",
  "Trigger Unit",
  "Tripped Power Circuit",
  "Ultraconducting Ablative Nanocable",
  "Unrestricted Hyperspace Telemetry",
    "Ward Console",
  ] },
  {
    rate: 0.85,
    items: [
  "Chromodynamic Tricarboxyls",
  "Eleutrium",
  "Isogen",
  "Megacyte",
  "Mexallon",
  "Morphite",
  "Neo-Jadarite",
  "Nocxium",
  "Pyerite",
  "Tritanium",
    "Zydrine",
  ] },
];

const BUYBACK_RATE_BY_ITEM_NAME = new Map<string, number>(
  BUYBACK_CATEGORIES.flatMap(({ rate, items }) =>
    items.map((name) => [name.toLowerCase(), rate] as const),
  ),
);

export function getBuybackRate(typeName: string): number {
  return BUYBACK_RATE_BY_ITEM_NAME.get(typeName.toLowerCase()) ?? DEFAULT_BUYBACK_RATE;
}
